server:
  port: 8091

spring:
  application:
    name: emazon_user_microservices
  datasource:
    url: jdbc:mysql://localhost/stock_db
    username: ${username}
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
